version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./environment/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./environment/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - postgres
    networks:
      - webapp

  php:
    build:
      context: ./environment/php
    container_name: app_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - webapp

  postgres:
    image: postgres:14-alpine
    container_name: app_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./environment/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questionario_ocai
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - webapp

networks:
  webapp:


volumes:
  postgres_data:
