version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - postgres

    networks:
      - webapp

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: app_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - webapp

  postgres:
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questionario_ocai
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - webapp