<!-- Footer -->
<footer class="footer bg-dark py-5">
    <div class="container grid grid-3">
        <!-- Grid iten 1 -->
        <div>
            <h1>UNIVATES EAD</h1>
            <p>Copyright &copy; 2022</p>
            <p>Lorem Ipsum</p>
        </div>
        <!-- Grid iten 2 -->
        <nav>
            <ul>
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                <li><a href="#">Link 3</a></li>
            </ul>
        </nav>
    </div>
</footer>